declare name "808 Cowbell";
declare version "0.1.0-experiment";
declare author "curlcomplex; circuit/oracle research includes TapTools by Timothy Place";
declare description "Single-note 808 cowbell candidate using two detuned square oscillators, filtering and decay; extended ratio/tone/drive controls; reference comparison pending.";
import("stdfaust.lib");
u=library("drums808aux.lib");
gate=button("gate[curlop:input]");
freq=hslider("freq[unit:Hz][scale:log][curlop:input]",540,220,1300,.001);
velocity=hslider("velocity[curlop:input]",1,0,1,.001);
accent=hslider("accent[curlop:input]",0,0,1,.001);
ratio=hslider("ratio[col:0][row:0]",1.48,1.2,1.9,.001);
decay=hslider("decay[unit:s][scale:log][col:1][row:0]",.42,.04,2.0,.001);
tone=hslider("tone[col:2][row:0]",.55,0,1,.001):u.sm;
drive=hslider("drive[col:3][row:0]",.08,0,1,.001):u.sm;
level=hslider("level[col:0][row:1]",.78,0,1,.001):u.sm;
h=gate>gate';
f=u.lat(h,freq);d=u.lat(h,decay);v=u.lat(h,velocity);a=u.lat(h,accent);r=u.lat(h,ratio);
p1=u.phase(h,f);p2=u.phase(h,f*r);
metal=.5*u.square(p1)+.5*u.square(p2);
filtered=metal:fi.resonbp(min(.4*ma.SR,f*(1.25+1.1*tone)),.7+1.2*tone,1):fi.highpass(1,250+1000*tone);
raw=filtered*u.env(h,d,.00015);
process=u.finish(raw,v,a,level,drive);
