declare name "808 Maracas";
declare version "0.1.0-experiment";
declare author "curlcomplex";
declare description "Single-note 808 maracas candidate; filtered-noise burst with extended tone/decay controls; reference comparison pending.";
import("stdfaust.lib");
u=library("drums808aux.lib");
gate=button("gate[curlop:input]");
freq=hslider("freq[unit:Hz][scale:log][curlop:input]",7200,2500,14000,.001);
velocity=hslider("velocity[curlop:input]",1,0,1,.001);
accent=hslider("accent[curlop:input]",0,0,1,.001);
decay=hslider("decay[unit:s][scale:log][col:0][row:0]",.045,.008,.35,.001);
tone=hslider("tone[col:1][row:0]",.55,0,1,.001):u.sm;
grit=hslider("grit[col:2][row:0]",.18,0,1,.001):u.sm;
level=hslider("level[col:3][row:0]",.75,0,1,.001):u.sm;
h=gate>gate';
f=u.lat(h,freq);d=u.lat(h,decay);v=u.lat(h,velocity);a=u.lat(h,accent);
filtered=no.noise:fi.resonbp(min(.42*ma.SR,f*(.75+.5*tone)),.8,1):fi.highpass(1,max(700,f*.35));
en=u.env(h,d,.00008);
raw=filtered*en*(1+.7*grit*ma.tanh(filtered*3));
process=u.finish(raw,v,a,level,.05+.25*grit);
