"""Generate the canonical Morph spectral bank and optional playback tables.

The authored spectra are independent work: no sample, firmware or manufacturer
waveform extraction. v2 keeps the Fourier coefficients as the reference/oracle;
v3 uses the same coefficients to generate static multiband lookup tables.
"""
from __future__ import annotations
import argparse, hashlib, json
from pathlib import Path
import numpy as np

HARMONICS = 64
CYCLE_SIZE = 8192
TABLE_SIZE = 256
# Dense log-spaced max-oscillator frequencies let table interpolation approximate
# v2's continuous 16--19 kHz harmonic taper, rather than hard harmonic bins.
BAND_FREQUENCIES = np.geomspace(20.0, 9000.0, 48)
NAMES = ['Sine','Soft','Saw','Hollow','Vowel','Organ','Glass','Edge']


def generate():
    n = np.arange(1, HARMONICS + 1, dtype=float)
    odd = n.astype(int) % 2
    c = np.stack([
        (n == 1).astype(float),
        odd / n**2,
        1 / n,
        odd / n,
        .4*(n == 1) + np.exp(-.18*(n-5)**2) + .5*np.exp(-.07*(n-13)**2),
        .9*(n == 1) + .6*(n == 2) + .4*(n == 4) + .25*(n == 8) + .2*(n == 16),
        .25*(n == 1) + odd*np.exp(-.07*(n-9)**2),
        .7*(n == 1) + 1/(n**.65),
    ])
    phase = 2*np.pi*np.arange(CYCLE_SIZE)/CYCLE_SIZE
    basis = np.sin(n[:, None]*phase)
    clean, driven, cycles = [], [], []
    for row in c:
        row = row*(.75/np.max(np.abs(row@basis)))
        wave = row@basis
        sat = np.tanh(4*wave)
        coeff = -np.fft.rfft(sat).imag[1:HARMONICS+1]*2/CYCLE_SIZE
        coeff *= .75/np.max(np.abs(coeff@basis))
        clean.append(row); driven.append(coeff); cycles.extend([wave, coeff@basis])
    return np.array(clean), np.array(driven), np.array(cycles)


def write_tables(path: Path, clean: np.ndarray, driven: np.ndarray) -> dict:
    path.parent.mkdir(parents=True, exist_ok=True)
    n = np.arange(1, HARMONICS + 1, dtype=float)
    phase = 2*np.pi*np.arange(TABLE_SIZE)/TABLE_SIZE
    basis = np.sin(n[:, None]*phase)
    values = []
    # Flatten order must match v3 flatIndex: band, frame, shape, drive, sample.
    for max_hz in BAND_FREQUENCIES:
        taper = np.clip((19000.0 - n*max_hz)/3000.0, 0.0, 1.0)
        for frame in range(len(NAMES)):
            for shape in (0, 1):
                tilt = (1-shape)/(1.0+.08*(n-1)*(n-1)) + shape
                for drive in (0, 1):
                    coeff = (driven if drive else clean)[frame] * tilt * taper
                    values.extend((coeff @ basis).tolist())
    text = (
        '// GENERATED by tools/modules/generate_morph_bank.py. Do not hand edit.\n'
        f'// {len(BAND_FREQUENCIES)} frequency bands x {len(NAMES)} frames x 2 shape x 2 drive x {TABLE_SIZE} samples.\n'
        'tableBank = waveform{' + ','.join(f'{x:.9g}' for x in values) + '};\n'
    )
    path.write_text(text)
    return {
        'table_size': TABLE_SIZE,
        'band_frequencies_hz': [float(x) for x in BAND_FREQUENCIES],
        'floats': len(values),
        'bytes_float32_equivalent': len(values)*4,
        'sha256': hashlib.sha256(text.encode()).hexdigest(),
        'interpolation': 'runtime linear phase; runtime log-frequency adjacent-band interpolation',
        'dimensions': 'max-oscillator-frequency band, frame, shape endpoint, drive endpoint, sample',
        'taper': 'same coefficient multiplier as v2 oracle: clamp((19000 - harmonic*maxHz)/3000, 0, 1)',
    }


def write(out: Path, table_out: Path | None = None):
    out.mkdir(parents=True, exist_ok=True)
    clean, driven, cycles = generate()
    lines = ['// GENERATED from generate_morph_bank.py. Do not hand edit.', 'import("stdfaust.lib");']
    for name, values in [('clean', clean), ('driven', driven)]:
        for i, row in enumerate(values):
            for harmonic, value in enumerate(row, 1):
                lines.append(f'{name}({i},{harmonic})={value:.17e};')
    content = '\n'.join(lines) + '\n'
    (out/'bank.lib').write_text(content)
    cycles.astype('<f4').tofile(out/'wavetable-cycles.f32')
    table_info = write_tables(table_out, clean, driven) if table_out else None
    info = {
        'schema': 3, 'names': NAMES, 'harmonics': HARMONICS, 'cycle_size': CYCLE_SIZE,
        'cycle_order': 'interleaved clean/driven per named frame',
        'clean_coefficients': clean.tolist(), 'driven_coefficients': driven.tolist(),
        'bank_sha256': hashlib.sha256(content.encode()).hexdigest(),
        'cycles_sha256': hashlib.sha256((out/'wavetable-cycles.f32').read_bytes()).hexdigest(),
        'normalization': 'Each authored frame endpoint is peak calibrated to .75 offline. No output/per-hit normalization.',
        'drive': 'FFT of tanh(4*clean), truncated to 64 sine harmonics and peak calibrated; playback blends clean/driven spectral endpoints.',
        'reference_rendering': 'v2 analytic Fourier/Clenshaw evaluation.',
        'playback_tables': table_info,
    }
    (out/'bank.json').write_text(json.dumps(info, indent=2)+'\n')
    return info


if __name__ == '__main__':
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--out', type=Path, required=True)
    p.add_argument('--table-out', type=Path)
    a = p.parse_args()
    info = write(a.out, a.table_out)
    print(json.dumps({'bank_sha256': info['bank_sha256'], 'playback_tables': info['playback_tables']}))
