// Offline topology fixture, NOT a YM2414 chip/audio emulator.
// Compiles the exact pinned ymfm output_4op body against tagged operators.
// The body is generated byte-for-byte into routing_body.inc; source and
// excerpt hashes are retained. No upstream source file is changed.
// ymfm excerpt: Copyright (c) 2021 Aaron Giles, BSD-3-Clause;
// see modules/tx81z/YMFM-LICENSE.txt and the retained upstream source.
#include <cstdint>
#include <iostream>
#include "ymfm.h"

namespace ymfm {
struct TaggedOperator {
    int32_t value = 0;
    mutable uint32_t observed_phase = 0;
    uint32_t phase() const { return 0; }
    int32_t compute_volume(uint32_t phase_value, uint32_t) const {
        observed_phase = phase_value;
        return value;
    }
    int32_t compute_noise_volume(uint32_t) const { return 0; }
};
struct TopologyRegisters {
    uint32_t algorithm = 0;
    uint32_t lfo_am_offset(uint32_t) const { return 0; }
    uint32_t ch_feedback(uint32_t) const { return 0; }
    uint32_t ch_output_any(uint32_t) const { return 1; }
    uint32_t ch_algorithm(uint32_t) const { return algorithm; }
    uint32_t noise_enable() const { return 0; }
};
// Test double deliberately uses the upstream class/method name so the
// extracted production method requires no textual rewriting.
template<class RegisterType> struct fm_channel {
    using output_data = ymfm_output<2>;
    TaggedOperator* m_op[4]{};
    RegisterType m_regs{};
    uint32_t m_choffs = 0;
    int32_t m_feedback[2]{};
    mutable int32_t m_feedback_in = 0;
    void output_4op(output_data&, uint32_t, int32_t) const;
    void add_to_output(uint32_t, output_data& output, int32_t result) const {
        output.data[0] += result;
    }
};
#include "routing_body.inc"
}

int main() {
    std::cout << "algorithm,basis,in2,in3,in4,carrier\n";
    for (uint32_t a=0; a<8; ++a) {
        for (uint32_t basis=0; basis<4; ++basis) {
            ymfm::fm_channel<ymfm::TopologyRegisters> ch;
            ymfm::TaggedOperator ops[4];
            // Even tag 2 cancels the production modulation >>1. The final
            // carrier sum is divided by 2 separately. No overflowing tags.
            ops[basis].value = 2;
            ch.m_regs.algorithm = a;
            for (unsigned i=0;i<4;++i) ch.m_op[i]=&ops[i];
            ymfm::ymfm_output<2> output{};
            ch.output_4op(output, 0, 32767);
            if (output.data[0] % 2) return 2;
            std::cout << a << ',' << basis << ',' << ops[1].observed_phase
                      << ',' << ops[2].observed_phase << ',' << ops[3].observed_phase
                      << ',' << output.data[0]/2 << '\n';
        }
    }
}
