#!/usr/bin/env python3
"""Generate a reference annular-plate Ritz basis and a passive modal Faust kernel.

The linear reference is a tapered Kirchhoff-Love plate, clamped on a small
central support and free at its outer boundary, with a positive approximate
shell-curvature foundation. This is NOT the full von Karman shell equations.
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import numpy as np
from numpy.polynomial import Legendre
from scipy.linalg import eigh

NMODES = 128
SUPPORT = 0.035
RADIUS = 0.22
THICKNESS = 0.0012
TAPER = 0.60
BELL = 0.28
HEIGHT = 0.12
E = 110e9
RHO = 8800.0
NU = 0.34
RELAXATION = 0.0025


def basis(r: np.ndarray, order: int = 24):
    """Ritz trial functions satisfy w=w'=0 at the support; edge is natural/free."""
    out = []
    variable = r - SUPPORT
    for j in range(order):
        leg = Legendre.basis(j, domain=[SUPPORT, 1.0])
        v=variable
        out.append([v*v*leg(r), 2*v*leg(r)+v*v*leg.deriv(1)(r),
                    2*leg(r)+4*v*leg.deriv(1)(r)+v*v*leg.deriv(2)(r)])
    return tuple(np.array(out)[:, k, :].T for k in range(3))


def reference_modes(count: int = NMODES, order: int = 24):
    nodes, weights = np.polynomial.legendre.leggauss(110)
    r = SUPPORT + (nodes + 1) * (1-SUPPORT)/2
    weight = weights * (1-SUPPORT)/2 * r
    w, wr, wrr = basis(r, order)
    t = 1-TAPER*r
    mass = w.T @ ((weight*t)[:, None] * w)
    # Nondimensional curvatures of a smooth raised bell z/R=H exp(-(r/b)^4).
    bellz = HEIGHT*np.exp(-(r/BELL)**4)
    kr = bellz*(16*r**6/BELL**8-12*r**2/BELL**4)
    kt = -4*bellz*r**2/BELL**4
    foundation = kr*kr + kt*kt + 2*NU*kr*kt
    bellmat = w.T @ ((weight*t*foundation)[:, None]*w)
    bowmat = w.T @ ((weight*t*8*(0.035**2)*(1+NU))[:, None]*w)
    D = E*THICKNESS**3/(12*(1-NU**2))
    raw = []
    grid = np.linspace(SUPPORT, 1.0, 129)
    tablebasis = basis(grid, order)[0]
    for m in range(19):
        hoop = wr/r[:, None] - m*m*w/(r*r)[:, None]
        shear = m*(wr/r[:, None]-w/(r*r)[:, None])
        wt = weight*t**3
        bend = (wrr.T @ (wt[:, None]*wrr) + hoop.T @ (wt[:, None]*hoop)
                + NU*(wrr.T @ (wt[:, None]*hoop)+hoop.T @ (wt[:, None]*wrr))
                + 2*(1-NU)*shear.T @ (wt[:, None]*shear))
        kb = D/(RHO*THICKNESS*RADIUS**4)*bend
        ks = RELAXATION*E/((1-NU**2)*RHO*RADIUS**2)*bellmat
        kw = RELAXATION*E/((1-NU**2)*RHO*RADIUS**2)*bowmat
        lam, vectors = eigh((kb+ks+kw + (kb+ks+kw).T)/2, mass)
        for n in range(min(17, order-3)):
            v = vectors[:, n]
            if (tablebasis @ v)[-1] < 0: v = -v
            shape = tablebasis @ v / (np.sqrt(2) if m == 0 else 1)
            # Explicit stiffness components enable a positive Rayleigh-quotient morph.
            pieces = np.array([v @ kb @ v, v @ ks @ v, v @ kw @ v])/(2*np.pi)**2
            normshape = (w @ v)**2*weight*t
            centroid = float(np.sum(r*normshape)/np.sum(normshape))
            for quadrature in range(1 if m == 0 else 2):
                raw.append(dict(m=m,n=n,quadrature=quadrature,f=float(np.sqrt(lam[n])/(2*np.pi)),
                                bend=float(pieces[0]),bell=float(pieces[1]),bow=float(pieces[2]),
                                centroid=centroid,shape=shape.tolist()))
    raw.sort(key=lambda x:(x['f'],x['m'],x['n'],x['quadrature']))
    # Select a broadband reduced basis, not merely the first (low) modes.
    # Full mode-density convergence is deliberately NOT claimed.
    axis=[x for x in raw if x['m']==0 and x['f']<16000][:8]
    pairs=[x for x in raw if x['m']>0 and x['quadrature']==0 and x['f']<16000]
    indices=list(range(8))+np.linspace(8,len(pairs)-1,(count-len(axis))//2-8).astype(int).tolist()
    selected=axis[:]
    for idx in indices:
        x=pairs[idx]; selected += [x, dict(x, quadrature=1)]
    selected.sort(key=lambda x:(x['f'],x['m'],x['n'],x['quadrature']))
    # Keep low and high frequencies interleaved for the connected nonlinear scatterer.
    half = len(selected)//2
    selected = [item for pair in zip(selected[:half],selected[half:]) for item in pair]
    return selected


def literal(x):
    return format(float(x), '.10g') if abs(x) > 1e-13 else '0.0'


def emit(modes: list[dict]) -> str:
    n = len(modes)
    lines = ['// Generated by scripts/generate_cymbal.py; do not hand-edit.',f'N = {n};',f'support = {SUPPORT};']
    for field, name in [('m','azimuth'),('quadrature','quadrature'),('f','referenceHz'),
                        ('bend','bendHz2'),('bell','bellHz2'),('bow','bowHz2'),('centroid','centroid')]:
        for i, mode in enumerate(modes):
            lines.append(f'{name}({i}) = {literal(mode[field])};')
    for i, mode in enumerate(modes):
        values = ','.join(literal(x) for x in mode['shape'])
        lines.append(f'radialTable({i},idx) = (waveform{{{values}}},int(idx)) : rdtable;')
    lines += ['radial(i,r) = (1-frac)*radialTable(i,j)+frac*radialTable(i,min(128,j+1)) with {',
              ' index = 128*min(1,max(0,(r-support)/(1-support))); j=int(index); frac=index-j; };']
    def route(pairs, nin, nout):
        return f'route({nin},{nout},('+','.join(f'({a},{b})' for a,b in pairs)+'))'
    excite=[]
    for i in range(n):
        excite += [(2*i+1,3*i+1),(2*i+2,3*i+2),(2*n+1,3*i+3)]
    shift=[((j+2)%(2*n)+1,j+1) for j in range(2*n)]
    unshift=[((j-2)%(2*n)+1,j+1) for j in range(2*n)]
    lines += [
        '// Fixed-arity routing makes the feedback state layout explicit.',
        'model = (step ~ si.bus(2*N)) <: project with {',
        ' rot(i,x,p,f) = d*(c*x+s*k),d*((0-s)*x+c*k) with {',
        '  w=2*ma.PI*min(0.42*ma.SR,max(0.00001,modeHz(i)))/ma.SR;',
        '  c=cos(w); s=sin(w); d=modeDecay(i); k=p+f*strikeShape(i); };',
        ' pair(x,p,y,q) = x,c*p+s*q,y,(0-s)*p+c*q with {',
        '  t=scatter*(x+y)/(1+abs(30*(x+y)));',
        '  c=(1-t*t)/(1+t*t); s=2*t/(1+t*t); };',
        ' step = '+route(excite,2*n+1,3*n)+' : par(i,N,rot(i))',
        '     : par(i,N/2,pair) : '+route(shift,2*n,2*n),
        '     : par(i,N/2,pair) : '+route(unshift,2*n,2*n)+';',
        ' project = (par(i,N,(!,_ : *(strikeShape(i)/sqrt(modalMass)))) :> _),',
        '           (par(i,N,(!,_ : *(pickup(i,0)))) :> _),',
        '           (par(i,N,(!,_ : *(pickup(i,1)))) :> _),',
        r'           (par(i,N,\(x,p).(x*x+p*p)) :> _);',
        '};']
    return '\n'.join(lines)+'\n'


def main():
    ap=argparse.ArgumentParser(); ap.add_argument('--out',default='build'); args=ap.parse_args()
    out=Path(args.out); out.mkdir(parents=True,exist_ok=True)
    modes=reference_modes()
    if len(modes)!=NMODES or not all(np.isfinite(x['f']) and x['f']>0 for x in modes):
        raise RuntimeError('Invalid reference modal solution')
    (out/'cymbal-kernel.lib').write_text(emit(modes))
    report={'model':'tapered annular Ritz plate + relaxed curvature foundation',
            'modes':NMODES,'support':SUPPORT,'radius_m':RADIUS,'thickness_m':THICKNESS,
            'reference_taper':TAPER,'reference_bell_ratio':BELL,'reference_bell_height_ratio':HEIGHT,
            'curvature_relaxation':RELAXATION,'parameters_calibrated_to_real_cymbal':False,
            'data':[{k:v for k,v in x.items() if k!='shape'} for x in modes]}
    (out/'reference-modes.json').write_text(json.dumps(report,indent=2)+'\n')
    print(f"Generated {NMODES} modes: {min(x['f'] for x in modes):.1f}--{max(x['f'] for x in modes):.1f} Hz")

if __name__=='__main__': main()
