"""Generate modal data and the explicit Faust state update from public equations.

The generated standalone .dsp is the actual source compiled/rendered by CI.
"""
from __future__ import annotations
import argparse, json, pathlib
import numpy as np
from modal_model import make_grid, ANGULAR_ORDERS, RADIAL_MODES, SAMPLES
ROOT=pathlib.Path(__file__).resolve().parents[1]

def generate(out: pathlib.Path):
    out.mkdir(parents=True,exist_ok=True)
    grid=make_grid(); data=[]
    for m in range(ANGULAR_ORDERS):
        for n in range(RADIAL_MODES):
            for geom in grid:
                row=geom[m]
                data.extend([row['bend'][n],row['membrane'][n],row['slope'][n]])
                data.extend(row['shape'][:,n])
    values=','.join(f'{x:.10g}' if '.' in f'{x:.10g}' or 'e' in f'{x:.10g}' else f'{x:.10g}.0' for x in data)
    lib='// Generated by scripts/generate_cymbal.py. No sampled audio.\n'
    lib+=f'tab(index) = (waveform{{{values}}},int(index)) : rdtable;\n'
    lib+=f'datum(i,g,f) = tab((i*9+g)*{SAMPLES+3}+f);\n'
    (out/'cymbal-modes.lib').write_text(lib)
    modes=[(m,n,p) for m in range(ANGULAR_ORDERS) for n in range(RADIAL_MODES) for p in range(1 if m==0 else 2)]
    N=len(modes); params=[s for k in range(N) for s in (f'x{k}',f'v{k}')]+['bxold','bvold','aold','lastres','lastforce']
    lines=[f'STATES={2*N+5};',f'step({",".join(params)}) = '+','.join([s for k in range(N) for s in (f'xn{k}',f'vn{k}')]+['bxnew','bvnew','anew','residual','fc'])+' with {']
    for k,(m,n,p) in enumerate(modes):
        u=m*RADIAL_MODES+n
        lines.extend([
            f'w{k}=omega({u},{k}); d{k}=den({u},{k});',
            f'a{k}=shape({u},pos)*angular({m},{p},angle)*ms*foot({u})*band({u},{k});',
            f'g{k}=blend({u},2)*angular({m},{p},0.371)*ms/sr*band({u},{k})/(1+pow(basefreq({u})/5000,2));',
            f'vf{k}=((1-sigma({u},{k})*dt-pow(w{k}*dt*0.5,2))*v{k}-w{k}*dt*x{k})/d{k};',
            f'xf{k}=x{k}+w{k}*dt*0.5*(v{k}+vf{k});',
            f'vn{k}=vf{k}+dt*(a{k}*fc-g{k}*fn)/d{k};',
            f'xn{k}=xf{k}+w{k}*h*(a{k}*fc-g{k}*fn)/d{k};'])
    summ=lambda term:'+'.join(term(k) for k in range(N))
    lines.extend([
        'active=max(aold,trig);',
        'contactold='+summ(lambda k:f'a{k}*x{k}/w{k}')+';',
        'contactfree='+summ(lambda k:f'a{k}*xf{k}/w{k}')+';',
        's0='+summ(lambda k:f'g{k}*x{k}/w{k}')+';',
        'sf='+summ(lambda k:f'g{k}*xf{k}/w{k}')+';',
        'ac=1/max(0.002,mb)+'+summ(lambda k:f'a{k}*a{k}/d{k}')+';',
        'ag='+summ(lambda k:f'g{k}*g{k}/d{k}')+';',
        'cross='+summ(lambda k:f'a{k}*g{k}/d{k}')+';',
        'bx=select2(trig,bxold,contactold);',
        'bv=select2(trig,bvold,3*velocity);',
        'd0=bx-contactold; df=bx+dt*bv-contactfree;',
        'ck=contactk*active; cd=contactd*active;',
        '// Unilateral contact discrete gradient and compression-only loss.',
        'cf(d)=ck*select2(d0>=0,select2(d>=0,0,0.5*d*d/max(1e-15,d-d0)),select2(d>=0,0.5*d0*d0/max(1e-15,d0-d),0.5*(d+d0)))+cd*max(0,max(0,d)-max(0,d0))/dt;',
        'cfd(d)=ck*select2(d0>=0,select2(d>=0,0,0.5*d*(d-2*d0)/pow(max(1e-15,d-d0),2)),select2(d>=0,0.5*d0*d0/pow(max(1e-15,d0-d),2),0.5))+cd*(d>max(0,d0))/dt;',
        'nf(s)=kappa*0.25*(s+s0)*(s*s+s0*s0);',
        'nfd(s)=kappa*0.25*(3*s*s+2*s*s0+s0*s0);',
        'iteration(d,s)=(d-(j22*r1-j12*r2)/det),(s-(-j21*r1+j11*r2)/det) with {',
        'r1=d-df+h*(ac*cf(d)-cross*nf(s)); r2=s-sf+h*(ag*nf(s)-cross*cf(d));',
        'j11=1+h*ac*cfd(d); j12=-h*cross*nfd(s); j21=-h*cross*cfd(d); j22=1+h*ag*nfd(s);',
        '// Expanded determinant avoids cancellation of large positive terms.',
        'det=1+h*(ac*cfd(d)+ag*nfd(s))+h*h*max(0,ac*ag-cross*cross)*cfd(d)*nfd(s); };',
        'solve(0)=_,_; solve(n)=solve(n-1):iteration;',
        'solution=(d0,s0):solve(10); dn=solution:_,!; sn=solution:!,_;',
        'fc=cf(dn); fn=nf(sn);',
        'residual=max(abs(dn-df+h*(ac*fc-cross*fn))/max(0.000001,abs(df)+abs(d0)),abs(sn-sf+h*(ag*fn-cross*fc))/max(0.000001,abs(sf)+abs(s0)));',
        'bxnew=bx+dt*bv-h*fc/max(0.002,mb); bvnew=bv-dt*fc/max(0.002,mb);',
        'anew=active*(1-((dn<(-0.0001))*(bvnew<0)));',
        '};'])
    lines.append(f'pickup({",".join(params)})=attach(left,energy+res+force),right with {{')
    for k,(m,n,p) in enumerate(modes):
        u=m*RADIAL_MODES+n
        lines.append(f'l{k}=shape({u},0.78)*angular({m},{p},0.41)*band({u},{k})*ms*basefreq({u})/(basefreq({u})+180);')
        lines.append(f'r{k}=shape({u},0.89)*angular({m},{p},1.47)*band({u},{k})*ms*basefreq({u})/(basefreq({u})+180);')
    lines.extend([
        'left=gain*('+summ(lambda k:f'l{k}*v{k}')+');',
        'right=gain*('+summ(lambda k:f'r{k}*v{k}')+');',
        'slopeNow='+summ(lambda k: f'(blend({modes[k][0]*RADIAL_MODES+modes[k][1]},2)*angular({modes[k][0]},{modes[k][2]},0.371)*ms/sr*band({modes[k][0]*RADIAL_MODES+modes[k][1]},{k})/(1+pow(basefreq({modes[k][0]*RADIAL_MODES+modes[k][1]})/5000,2)))*x{k}/omega({modes[k][0]*RADIAL_MODES+modes[k][1]},{k})')+';',
        'surfaceNow='+summ(lambda k: f'shape({modes[k][0]*RADIAL_MODES+modes[k][1]},pos)*angular({modes[k][0]},{modes[k][2]},angle)*ms*foot({modes[k][0]*RADIAL_MODES+modes[k][1]})*band({modes[k][0]*RADIAL_MODES+modes[k][1]},{k})*x{k}/omega({modes[k][0]*RADIAL_MODES+modes[k][1]},{k})')+';',
        'energyValue=0.5*('+summ(lambda k:f'x{k}*x{k}+v{k}*v{k}')+')+0.25*kappa*pow(slopeNow,4)+aold*(0.5*max(0.002,mb)*bvold*bvold+0.5*contactk*pow(max(0,bxold-surfaceNow),2));',
        'energy=attach(energyValue:hbargraph("energy",0,100),energyValue:(max~_):hbargraph("energy_peak",0,100));',
        'res=lastres:(max~_):hbargraph("solver_residual_peak",0,1);',
        'force=attach(lastforce:hbargraph("contact_force",0,10000),(lastforce:(max~_):hbargraph("contact_force_peak",0,10000))+((lastforce>0):(+~_):hbargraph("contact_samples",0,1000000000)));',
        '};'])
    network='\n'.join(lines)+'\n'
    (out/'cymbal-network.lib').write_text(network)
    source=(ROOT/'dsp/cymbal.dsp').read_text().replace('import("cymbal-modes.lib");',lib).replace('import("cymbal-network.lib");',network)
    (out/'cymbal-standalone.dsp').write_text(source)
    meta={'modes':N,'radial_families':RADIAL_MODES,'angular_orders':ANGULAR_ORDERS,'bell_geometries':9,'basis':'clamped-hole free-rim tapered shallow shell, Rayleigh-Ritz; condensed in-plane motion','nonlinearity':'positive rank-one quartic stretching potential, implicit discrete-gradient update','data_values':len(data),'reference_frequency_min_hz':float(min(np.sqrt(g['bend']+g['membrane']).min() for g in grid[4])),'reference_frequency_max_hz':float(max(np.sqrt(g['bend']+g['membrane']).max() for g in grid[4]))}
    (out/'model.json').write_text(json.dumps(meta,indent=2)+'\n')
    print(json.dumps(meta))
    return meta

if __name__=='__main__':
    parser=argparse.ArgumentParser(); parser.add_argument('--out',type=pathlib.Path,default=ROOT/'build/cymbal')
    generate(parser.parse_args().out)
